# Generated by Django 3.2.7 on 2021-12-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_auto_20211124_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Empty title', max_length=30, verbose_name='Title'),
        ),
    ]
