# Generated by Django 2.2.12 on 2021-12-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=43, verbose_name='Title'),
        ),
    ]
