# Generated by Django 2.2.12 on 2021-10-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last_name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone_number')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='Position')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('blank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CV.Blank')),
                ('issue_area', models.TextField(default=None, verbose_name='Issue')),
            ],
            bases=('CV.blank',),
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('blank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CV.Blank')),
                ('url', models.CharField(default=None, max_length=150, null=True, verbose_name='Url')),
                ('technologies', models.TextField(default=None, verbose_name='Technologies')),
                ('languages', models.CharField(max_length=150, null=True, verbose_name='Languages')),
                ('motivation', models.TextField(default=None, verbose_name='Motivation')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.Position', verbose_name='Position')),
            ],
            bases=('CV.blank',),
        ),
    ]
